### ISSUE TITLE
rubocop導入

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#15]
静的コード解析のGemを導入すること。

Gemfileに、
- rubocop
- rubocop-rails
- rubocop-rspec

の3つを入れること。

onkcopリポジトリ(https://github.com/onk/onkcop)の、config下のファイルをコピーして、
config/rubocop/
の下にペーストすること。対象ファイルは、performance.yml以外全部。

設定ファイル `.rubocop.yml` を作成し、このように入力すること。

```
require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - "config/rubocop/rails.yml"
  - "config/rubocop/rubocop.yml"
  - "config/rubocop/rspec.yml"

AllCops:
  TargetRubyVersion: *.*.*
  TargetRailsVersion: *.*.*.*
```
